#! /bin/bash

sxhkd &
compton -f &
feh --bg-scale ~/Obrazy/wallpaper/mlake.jpg &
~/.config/polybar/scripts/launch.sh &
nm-applet &&
xsetroot -cursor_name left_ptr &

if [ ! -z $(xrandr |grep ' connected' |grep 'HDMI' |awk '{print $1}') ]; then
    bspc monitor eDP-1 -d 1 3 5 7 9
    bspc monitor HDMI-1 -d 2 4 6 8 0
else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
fi


#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gnome-calendar state=floating
